import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import AuthWrapper from "./AuthWrapper";

export const metadata: Metadata = {
  title: "sevedn edu paltformasining admin paneli",
  icons: {
    icon: "./image/logo.png"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthWrapper>
          <main className="md:pl-[300px] min-h-screen">{children}</main>
        </AuthWrapper>
      </body>
    </html>
  );
}
